Repository Jaunty-Jackals/jaunty-jackals, pull requests merged in 2021-07, with the labels that each got.

#2 Interface
  .gitignore
  bin/demo.py
  bin/utils/__init__.py
  bin/utils/palettes/__init__.py
  bin/utils/palettes/nord.json
  bin/utils/palettes/palettes.py
  dev-requirements.txt
  tox.ini
Labels: core, enhancement

#4 added base minesweep code
  minesweep/minesweep.py
  minesweep/utils.py
Labels: core, enhancement

#5 Merge interface to main
  demo.py
  minesweep/__init__.py
Labels: enhancement

#6 Introduce battleship game
  battleship/client.py
  battleship/color.py
  battleship/game.py
Labels: core, enhancement

#7 Interface
  battleship/__init__.py
  demo.py
Labels: core, enhancement

#11 Interface
  demo.py
  dev-requirements.txt
  utils/__init__.py
  utils/palettes/__init__.py
  utils/palettes/nord.json
  utils/palettes/palettes.py
Labels: enhancement

#12 Interface
  tox.ini
  utils/palettes/palettes.py
Labels: bug

#14 Interface
  demo.py
  dev-requirements.txt
  utils/assets/__init__.py
  utils/assets/graphics/__init__.py
  utils/assets/sound/__init__.py
  utils/palettes/palettes.py
Labels: Linux, MacOS, Windows, enhancement

#20 Interface
  .pre-commit-config.yaml
  bin/play_sounds/__init__.py
  bin/play_sounds/base.py
  tox.ini
Labels: bug

#22 Interface
  bin/demo.py
  bin/minesweep/minesweep.py
  bin/utils/macros/handy.py
  bin/utils/palettes/palettes.py
Labels: enhancement

#23 Battleship
  bin/battleship/client.py
  bin/battleship/console.py
  bin/battleship/game.py
Labels: core, enhancement

#31 Interface
  .gitignore
  README.md
  tox.ini
Labels: documentation

#32 Interface
  bin/demo.py
  bin/utils/palettes/palettes.py
Labels: bug

#33 Connectfour
  bin/ConnectFour/README.md
  bin/ConnectFour/sound_paths.py
  bin/ConnectFour/text_arts.py
  bin/blessedConnectFour.py
  bin/utils/sound/cnct4_drop.wav
Labels: core, enhancement

#34 Add tetris game
  bin/demo.py
  bin/tetris.py
  bin/tetris/README.md
  bin/tetris/__init__.py
  bin/tetris/app.py
  bin/tetris/core.py
  bin/tetris/exceptions.py
  bin/tetris/user_interface.py
  bin/tetris/utils.py
Labels: enhancement
